name: basf_flutter_components
description: A collection of BASF Style components
version: 2.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: BasfIcons
      fonts:
        - asset: assets/fonts/BasfIcons.ttf
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: fonts/roboto/Roboto-ThinItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/roboto/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/roboto/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/roboto/Roboto-BlackItalic.ttf
          style: italic
          weight: 900
